version: '3.8'
services:
  web:
    build: ./web
    environment:
      - DSN=utente:password@tcp(database:3306)/mydb
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: utente
      MYSQL_PASSWORD: password
    ports:
      - "3306"
    volumes:
      - ${PWD}/init-db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
